Main node <> Worker Service communication using socket.io
Valavanca/benchmark pull request #3
Opened 2018-08-09 20:34 UTC by YevheniiSemendiak

2018-08-15 13:16 UTC, dpukhkaiev requested changes
MaxTimeToRunExperiment must be explained. 
Method work(self, task) as well

2018-08-20 15:41 UTC, RomanKosovnenko approved these changes
nothing critical

2018-08-20 17:13 UTC, Valavanca approved these changes

2018-08-20 18:05 UTC, YevheniiSemendiak commented
Required changes from @dpukhkaiev have been made, majority of approves got, merging.

2018-08-20 18:05 UTC, merged